# Generated by Django 5.2.7 on 2025-11-22 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App33', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=32)),
                ('salt', models.CharField(max_length=32)),
                ('dk', models.CharField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='App33.user')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='App33.role')),
            ],
        ),
    ]
