# Generated by Django 5.2.8 on 2025-11-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App33', '0002_role_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='create_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='role',
            name='delete_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='role',
            name='read_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='role',
            name='update_level',
            field=models.IntegerField(default=0),
        ),
    ]
